<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID_company_code</name>
   <tag></tag>
   <elementGuidId>63e3e5a3-d6c5-476c-abfd-31354ac9c2a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='employee[first_name]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;employee[first_name]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d0a35d4-3fbb-452f-b8ac-cd1892131173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input--full </value>
      <webElementGuid>2a5636cc-d838-4443-995b-fbd66a78f425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03bfc871-c520-48af-ae12-289a35a89692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employee[first_name]</value>
      <webElementGuid>08f94e22-b61d-4c56-b1e0-9a546c592951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>職場氏名(名)</value>
      <webElementGuid>ac82692d-81b6-43d5-8e39-e54891f0c0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic_info_company&quot;)/div[@class=&quot;form-list form-list--employee permission--basic_info_company&quot;]/div[@class=&quot;form-list__content&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;form-list__item&quot;]/input[@class=&quot;input--full&quot;]</value>
      <webElementGuid>fdc352fc-67de-474c-90e9-43b9edc8005a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f705963d-5e8a-405f-9197-b2c2aa439439</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='employee[first_name]']</value>
      <webElementGuid>976fb95a-e32e-4fdf-b677-3a6614f66fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic_info_company']/div/div/div/div[4]/input</value>
      <webElementGuid>994ed2b5-8edf-4824-a6f2-e1934b8dc279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>fe67eb98-5733-4e07-b2d2-6c901a612e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'employee[first_name]' and @placeholder = '職場氏名(名)']</value>
      <webElementGuid>582dc527-123a-4c5b-8675-0e049ecb1be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='employee[last_name]']</value>
      <webElementGuid>dd9e8856-45e9-4b0f-b63b-1085e7e370c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic_info_company']/div/div/div/div[3]/input</value>
      <webElementGuid>2696beab-b41a-4001-b9a5-dc2d3ac0152f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>978d6cb1-460d-47be-9f04-560ce1b164de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'employee[last_name]' and @placeholder = '職場氏名(氏)']</value>
      <webElementGuid>e4202aa2-8e6c-471b-8ddd-99f45545095b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='employee[code]']</value>
      <webElementGuid>b1823769-2f23-4a5b-ad31-9b606c135d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic_info_company']/div/div/div/div/input</value>
      <webElementGuid>0d3ae0da-3e20-46f1-a5dd-d0ba6e462653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>5d82f925-fb3c-4c61-b698-4bbabc521e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'employee[code]' and @placeholder = '0000000000']</value>
      <webElementGuid>60fffaa9-afe1-4ea6-8ec9-30b381417686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='company_code']</value>
      <webElementGuid>8d63d7b0-3d3d-420a-91b8-953ebd7fdf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/input</value>
      <webElementGuid>8bc1fd28-d6a7-47c1-87ff-28942a7e4fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'company_code' and @placeholder = '企業ID']</value>
      <webElementGuid>e79e7720-a695-443f-a371-9d465cab369d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
