<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__code_or_email</name>
   <tag></tag>
   <elementGuidId>da67b06e-f314-49e4-a2a1-235645894aad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='code_or_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;code_or_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dea41f7-94c3-4a50-bb08-ecfc84e4819a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-input--text</value>
      <webElementGuid>29ecc646-bb23-489d-9f1e-067d283fbae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>716d6499-2cfa-41c5-af28-4c18d6c3316b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code_or_email</value>
      <webElementGuid>77b34483-60cc-4a96-a65f-07ae2aa20b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>社員番号　もしくは　メールアドレス</value>
      <webElementGuid>1371987c-b707-4f45-9aac-92d9d4f62890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrapper login-page&quot;]/section[@class=&quot;main-area&quot;]/section[@class=&quot;login-area&quot;]/form[@class=&quot;login-form&quot;]/dl[@class=&quot;login-form__item&quot;]/dd[1]/input[@class=&quot;login-input--text&quot;]</value>
      <webElementGuid>4210f74a-b284-4f79-abf5-8f57249ab110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='code_or_email']</value>
      <webElementGuid>af811b41-6634-41ce-a938-24a01dd2ceec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dl[2]/dd/input</value>
      <webElementGuid>f4e7f9ef-b5d9-489e-aa2a-3084e33ce5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code_or_email' and @placeholder = '社員番号　もしくは　メールアドレス']</value>
      <webElementGuid>383b794c-8680-4d19-bec4-a3bccbb28f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
